version: "3"

services:
  envoy:
    # build:
    #   context: /appimg/build/envoy
    image: envoy:1.0.0
    container_name: envoy
    ports:
      - 21001:21001
      - 21002:21002
      - 21003:9901
    volumes:
      - /appimg/resources/envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - /applog/envoy/:/applog/
    environment:
      - TZ=Asia/Seoul
    networks:
      - dockernet

  nginx:
    # build:
    #   context: /appimg/build/nginx
    image: nginx:1.0.0
    container_name: nginx
    ports:
      - 31011:31011
    volumes:
      - /apprun/:/apprun/
      - /appimg/resources/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /appimg/resources/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /applog/nginx/:/var/log/nginx/
    environment:
      - TZ=Asia/Seoul
    networks:
      - dockernet

networks:
  dockernet: {}
