version: "3"

services:
  envoy:
    build:
      context: /appimg/build/envoy
    container_name: envoy
    ports:
      - 21001:21001
      - 9901:9901
    volumes:
      - /appimg/resources/envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - /applog/envoy/:/var/log/
    networks:
      - dockernet

  nginx:
    build:
      context: /appimg/build/nginx
    container_name: nginx
    ports:
      - 31001:31001
    volumes:
      - /apprun/testweb/:/apprun/testweb/
      - /appimg/resources/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /appimg/resources/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /applog/nginx/:/var/log/nginx/
    networks:
      - dockernet

networks:
  dockernet: {}
