version: "3"

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    ports:
      - 3000:3000
      - 2222:2222
    volumes:
      # - /appimg/resources/gitea/app.ini:/data/gitea/conf/app.ini
      - /applog/gitea/:/data/gitea/log/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # - /home/git/.ssh/:/data/git/.ssh
    environment:
      - USER_UID=1002
      - USER_GID=1002
    networks:
      - gitea
    restart: always

networks:
  gitea:
    external: false
